name: Check Zsh syntax

run-name: Check Zsh on ${{ github.ref_type }} ${{ github.event_name }}

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
    paths:
      - '**.zsh'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.zsh'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zsh-check:
    runs-on: ubuntu-latest
    name: Check Zsh syntax
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up Homebrew
        id: homebrew-setup
        uses: Homebrew/actions/setup-homebrew@1f8e202ffddf94def7f42f6fa3a482e821489f9c # 2026.07.10.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Homebrew prefix
        uses: Homebrew/actions/cache-homebrew-prefix@1f8e202ffddf94def7f42f6fa3a482e821489f9c # 2026.07.10.1
        with:
          install: zsh
          uninstall: true
          workflow-key: ${{ github.workflow }}
      - name: Check zsh syntax
        working-directory: ./src/fns
        run: |
          checked=0; err=0
          while read -r file; do
            if ! errmsg="$(zsh -fn -- "$file" 2>&1)"; then
              echo "::error file=${file}::${errmsg}"; ((++err))
            fi; ((++checked))
          done < <(find . -name '*.zsh' -type f)
          echo "Check **$checked** files: **$err** error(s)" >> "$GITHUB_STEP_SUMMARY"
          [[ $err -eq 0 ]] || exit 1

  zsh-lint:
    runs-on: ubuntu-latest
    name: Lint Zsh functions
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: actions/setup-go@v7
        with:
          cache: false
          go-version: "1.27"
      - name: Install linter
        run: go install github.com/z-shell/zsh-lint/cmd/zsh-lint@v1.1.0
      - name: Run linter on zsh functions
        working-directory: ./src/fns
        run: zsh-lint --format=json functions/*.zsh functions/private/*.zsh > ${{ runner.temp }}/${{ job.check_run_id }}.json
      - name: Linter output
        env:
          NO_COLOR: ${{ true }}
        run: |
          out="${{ runner.temp }}/${{ job.check_run_id }}.json"
          echo "Check **$(jq '.summary.files' "$out")** files: **$(jq '.summary.errors' "$out")** error(s)\n\n```json\n$(jq --indent 2 '.summary' "$out")\n```" >> "$GITHUB_STEP_SUMMARY"
          n=$(jq '.diagnostics | length' "$out")
          for ((i=0; i < n; i++)); do
            [[ $(jq ".diagnostics[$i].severity") == "error" ]] || continue
            file=$(jq ".diagnostics[$i].file" $out)
            line=$(jq ".diagnostics[$i].range.start.line" $out)
            endLine=$(jq ".diagnostics[$i].range.end.line" $out)
            title=$(jq ".diagnostics[$i].rule" $out)
            msg=$(jq ".diagnostics[$i].message" <<< $out)
            echo "::error file=${file},line=${line},endLine=${endLine},title=${title}::${msg}"
          done
